language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: EmZkuIWCLQpq3BR4Oy7AgGKAeaxMY21JtQ8IPtYzn5lZVsGGICQ1c7XqvD9WEbqB3QX3vNAfs+YZ74YDLUnauoxoHAplfVuDDeHlPkkVKd06mG+nI+b4HspQoEp+k2wVfg589UAlOMYQBc8QKXioIItNTBfVwSSykJNwaxDOu9E=
  - secure: IR+mCeNjVekjczL/zUOkYsaqQnC6XMowotQjOfKAsLCJr075KY645Bhp7khV4vPZ8pNtSJ7FGJRtek08TRVJL5LOawOQ3sIDcPCs3M2X03ZZ7BYHxSZcCOI0RQ6mcpdZQpntBAnfu63wap1MaB94ZaXW3zg2aAkryb0hVGVgSJc=
