// Generated by CoffeeScript 1.8.0
(function() {
  var Bam;

  module.exports = Bam = {
    Backbone: require('./backbone'),
    Underscore: require('./underscore'),
    Router: require('./router'),
    View: require('./view'),
    Model: require('./model'),
    Collection: require('./collection')
  };

}).call(this);
