// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    Backbone: require('./backbone'),
    Router: require('./router'),
    View: require('./view'),
    Model: require('./model'),
    Collection: require('./collection')
  };

}).call(this);
