// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Backbone: require('backbone'),
    Collection: require('./collection'),
    Model: require('./model'),
    View: require('./view'),
    Decoratable: require('./decoratable')
  };

}).call(this);
