// Generated by CoffeeScript 1.6.3
/*
Convenience entry point if someone just wants to `require('bam')`
*/


(function() {
  module.exports = {
    Collection: require('./collection.js'),
    Model: require('./model.js'),
    View: require('./view.js'),
    Decoratable: require('./decoratable.js')
  };

}).call(this);
